version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: food_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: food_delivery
      MYSQL_USER: fooduser
      MYSQL_PASSWORD: foodpassword
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  backend:
    build: "./backend"
    container_name: food_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/food_delivery
      SPRING_DATASOURCE_USERNAME: fooduser
      SPRING_DATASOURCE_PASSWORD: foodpassword

  frontend:
    build: ./frontend
    container_name: food_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

    
    




