version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: food_delivery
    ports:
      - '3306:3306'
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/food_delivery?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    ports:
      - '8080:8080'
  
  frontend:
    build:
    ports:
      - '5173:5173'
    depends_on:
      - backend
      
volumes:
  dbdata:
    